### ISSUE TITLE
[v0.1.5] Small freeze after casting fireball

### ISSUE THREAD

**Issue by Teeyenoh** [Teeyenoh/zephis#1]
@JuiceWarrior can you confirm this?

**Comment by JuiceWarrior** [comment]
Yup

**Comment by JuiceWarrior** [comment]
BIG freeze after casting more than 1 too :)

**Comment by Teeyenoh** [comment]
Very strange, this only seems to happen when running from the jar file and not in Eclipse :-/

**Comment by Teeyenoh** [comment]
Can you find anything else that causes a similar freeze?

**Comment by Teeyenoh** [comment]
Should be fixed with v0.1.6 - confirm? @JuiceWarrior

**Comment by JuiceWarrior** [comment]
Works! Now stop putting up issues! This is MY job!
