### ISSUE TITLE
[v0.1.0-alpha] I swear to God, Dylan. If you delete these again, I'm disowning you

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#1]
Things that need fixing:

- More menu colours!
- Health doesn't lock at 0!
- Battle UI looks really bad!
- Can't do anything during combat!
- Game is physically unplayable!
- Need character portraits!

**Comment by JuiceWarrior** [comment]
Frost Dragon does way too much damage for this early in the game too

**Comment by JuiceWarrior** [comment]
I don't like classes being random either

**Comment by Teeyenoh** [comment]
For future reference, please put different problems into seperate issues so they can be tracked seperately :-)

**Comment by Teeyenoh** [comment]
Health now locks at 0 on my end, awaiting commit
Battle UI is very temporary
Combat is now playable on my end, awaiting commit
Still need to implement movement etc.!
Gonna steel the FFIV portraits for now lmao

**Comment by Teeyenoh** [comment]
Frost Dragon is just a test enemy, won't be like that in the real game
Random classes is an artifact from a test, classes won't be random in the full game
