### ISSUE TITLE
[v0.2.0.2-alpha (Seriously, Dylan?)] Dirt tiles

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#14]
The Dirt tiles don't properly align with the short and long grass tiles, trapped in a perpetual state of being too high up.

Please lower the dirt tile so it is flushed well with the background.

**Comment by Teeyenoh** [comment]
That's the player! And it's 12 pixels higher up so that when it's an actual player textures, the feet appear to be in the middle of the tile and not the bottom :-)
