### ISSUE TITLE
[v0.2.0.2-alpha] Grass tiles

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#15]
Both the short grass and long grass tiles don't properly align with each other. The long grass is too high up and hence does not appear to be apart of the actual background, merely floating in front of it.

Please lower the long grass tiles so they are flushed better with the background.

**Comment by Teeyenoh** [comment]
I don't understand! That's so they appear more like they're in the middle of the tile :-)

**Comment by JuiceWarrior** [comment]
A good word of advice, don't put things in the middle of the tiles, put them in the bottom, centred. It'll look MUCH better :)
