### ISSUE TITLE
[v0.2.0.2-alpha] Gaps in long grass tiles

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#16]
There're really obvious gaps at the tops of the long grass tiles where the shorter grass is able to be seen, this is especially jarring where long grass tiles are abundant in large patches.

Please have the long grass cover the entire tile, instead of simply the bottom portion, I think it could help long grass appear denser, which I think is what you were originally going for.

**Comment by Teeyenoh** [comment]
I know what you mean, I'll have a look at doing this :-)
