### ISSUE TITLE
[v0.2.0.2-alpha] Long grass tile physics

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#17]
The long grass tiles behave very strangely when walking across them. The grass seems to take too long to update and hence it can take a while for the grass to return to its original state after the dirt has moved off the tile.

Something tells me these intermediate sprites for the animations need to be removed, and instead having a simple "player stood on long grass tile" and "player NOT stood on long grass tile" states without the strange delay between animation updates. This should help improve the 'seamlessness' (not even sure if that's a real word...) of the animations in the game, combined with the density I mentioned earlier.

Also, when entering a grass block from in front or behind, it definitely looks like I'm dropping onto it from above. Slight perspective issue :P

**Comment by Teeyenoh** [comment]
Hmmm, I get this. Let me have a play around with the texture! I'll have to do very temporary ones, but they should suffice to give a general idea :-)

**Comment by JuiceWarrior** [comment]
You could also have a sprite where the grass appears slightly in front of the player so it actually looks like you're walking through long grass

**Comment by Teeyenoh** [comment]
Outdated, I have new ideas for this :-)
