### ISSUE TITLE
The time has come...

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#18]
Well, here we are again. 3 weeks have passed since the last update.

You know what this means don't you...?

**Comment by Teeyenoh** [comment]
Yes, the time has come! Charlotte and I have been working out arses of and the time for testing alpha version 0.3.0 is almost upon us! Expect to see a working inventory system, save files, health bars and a lot more in the next couple of days!

**Comment by JuiceWarrior** [comment]
But alas, more than a week later and still nothing :P

**Comment by JuiceWarrior** [comment]
A further 3 weeks later and nothing new to test. Dylan is really bad at keeping up with his own schedule.
