### ISSUE TITLE
[v0.4.2-alpha] Slight concern...

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#19]
Okay, so I have a bit of a problem here... I don't actually have any idea what I'm supposed to be doing or how to do anything.

I don't understand why there's a missing block that one white square moves up to, then stops moving.

I also can't interact with anything it seems.

**Comment by Teeyenoh** [comment]
At the moment I'm just making sure it doesn't crash with the new systems :-)

**Comment by Teeyenoh** [comment]
Unneeded
