### ISSUE TITLE
[v0.4.4-alpha] Missing block

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#20]
The missing block remains after version 0.4.2-alpha, appears to serve no purpose.

It's still blue. In case you were wondering...

**Comment by Teeyenoh** [comment]
I designed that missing texture myself! I'll do this at some point :-P

**Comment by JuiceWarrior** [comment]
The missing block tile has been replaced with a long grass tile in 0.4.5-alpha - functionally identical.

**Comment by Teeyenoh** [comment]
As intended :-)
