### ISSUE TITLE
[v0.4.4-alpha] Unstoppable force.

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#21]
The other paper aeroplane is impossible to kill. It's too tough for me.

Dylan tells me it's possible, but I don't believe him.

I've tried at least 10 times now, spamming Z as fast as I can.

It's impossible.

**Comment by Teeyenoh** [comment]
I promise it is! Keep trying :-P

**Comment by JuiceWarrior** [comment]
This has been fixed in 0.4.5-alpha.
