### ISSUE TITLE
[v0.4.5-alpha] After death

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#23]
After the player character dies, enemies will continue to attack and move onto the player tile, huddling together in a tight space attacking.

This, consequently, causes the enemies to infinitely kill each other due to their constant respawning.

They don't seem too distressed by it, though.

**Comment by Teeyenoh** [comment]
A very interesting bug! However, I won't fix it, as "after death" won't actually exist in the game once saves are implemented :-)
