### ISSUE TITLE
[v0.4.5-alpha] Menu problems

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#24]
The options 'Abilities' and 'Throw' within the menu do not serve a purpose and have no function associated with them.

**Comment by Teeyenoh** [comment]
I'll be implementing abilities in v0.4.6-alpha, but throwing will have to wait until the inventory system :-)

**Comment by JuiceWarrior** [comment]
Abilities are still not implemented by v0.4.6-alpha, despite plans to include it.
