### ISSUE TITLE
[v0.4.5-alpha] Enemy A.I.

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#25]
Enemies are able to move onto the player character's tiles, phasing into their bodies. They will immediately leave after they've entered and this does not seem to be limited by the directions the enemies are entering from.

**Comment by Teeyenoh** [comment]
I think that this is caused by the ball spells claiming your tile and then leaving it, making the enemies think it's an empty tile :-) double check this for me? They shouldn't do it before you use a ball spell

**Comment by JuiceWarrior** [comment]
This is incorrect. It can happen regardless of spell used.

**Comment by JuiceWarrior** [comment]
Standing on the tile they spawn on can make it happen more frequently

**Comment by JuiceWarrior** [comment]
This is still an issue in v0.4.6-alpha.

**Comment by JuiceWarrior** [comment]
Updated in v0.5.0-alpha. There no longer appear to be enemies in the overworld like previous updates. Combat does not appear to be possible.
