### ISSUE TITLE
[v0.4.5-alpha] Balancing

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#26]
It seems the "-ball" spells tend to deal more damage than the "-whip" spells.

Considering the "-whip" spells have much shorter range, deal substantially less damage and have a cooldown effect which prevents spamming, there doesn't seem to be much of a reason to bother with "-whip" spells when compared to "-ball" spells, whose only possible deterrent is the higher MP investment.

This should be fixed by giving "-ball" spells more deterrents or by making "-whip" spells more viable.

**Comment by Teeyenoh** [comment]
The ball spells should also be on the global cooldown, my bad :-) as for balancing, the ball spells will be harder to acquire and the whip spells will benefit from melee combat skills as well, so they should be a bit more balanced once that's implemented :-)

**Comment by JuiceWarrior** [comment]
This has been changed in v0.4.6-alpha. Now every attack does minuscule damage against the enemies, making the game more balanced, admittedly; but much, MUCH less fun.

**Comment by JuiceWarrior** [comment]
Updated in v0.5.0-alpha. There no longer appear to be enemies in the overworld like previous updates. Combat does not appear to be possible.
