### ISSUE TITLE
[v0.1.0-alpha] Map and movement issues!

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#3]
Movement is too fast
Change 8-way direction to 4-way direction (potentially a result of the high speed)
Can travel through cliffs
Hitboxes do not fit to objects in the environment
Party menu is gone?

**Comment by JuiceWarrior** [comment]
Huh... Almost 3 weeks since the last update. Me thinks a restart is imminent... Again...

**Comment by Teeyenoh** [comment]
Nope! Update tomorrow :-)
