### ISSUE TITLE
[v0.5.0-alpha] Missing squares

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#30]
There is a lone missing square just NW of the house. It seems to be the only block of its kind, not counting the debug hotbar

**Comment by Teeyenoh** [comment]
Could you attach a picture?

**Comment by JuiceWarrior** [comment]
![thing](https://user-images.githubusercontent.com/23152872/31850298-89cc5928-b647-11e7-935e-1d6f858cf8bf.png)

It's the only one I could find.

**Comment by Teeyenoh** [comment]
Ah right, that's an old map now so it should be sorted :-)
