### ISSUE TITLE
[v0.5.0-alpha] Movement improvements

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#31]
I feel a run button should be implemented to allow easier testing in a larger environment like this current build.

**Comment by Teeyenoh** [comment]
Agreed, what button would you suggest? Left shift?

**Comment by JuiceWarrior** [comment]
Left shift would work. Alternatively, further down the line, you could add the option to permanently change movement speed in the menu, or something.

**Comment by Teeyenoh** [comment]
Implemented in dc6d695
