### ISSUE TITLE
[v0.5.2-alpha] Missing Block

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#32]
There is a sly missing block, hiding behind a fence, West of the house.

He almost thought he could trick me with his shenanigans!
![error](https://user-images.githubusercontent.com/23152872/31910533-b6cc069a-b835-11e7-86aa-aec9ce832759.png)

**Comment by Teeyenoh** [comment]
No clue what that is! My bad!

**Comment by Teeyenoh** [comment]
Fixed in commit 4700af6
