### ISSUE TITLE
[v0.5.2-alpha] Clicking issue

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#34]
Okay, I have no idea what this is, but whenever I click on a tile, it changes to a 'missing' block. Clicking and dragging doesn't work.

**Comment by JuiceWarrior** [comment]
Missing tiles formed from clicking disappear upon reloading the game.

**Comment by Teeyenoh** [comment]
This is part of the map creator that should have been turned off for the release version. Fixed in commit ea4a16a0
