### ISSUE TITLE
[v0.5.2-alpha] Save file crash

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#36]
Deleting the save file causes the game to crash with a BufferUnderflowException error.

Don't purposefully delete your saves, people

**Comment by JuiceWarrior** [comment]
Closing the game leads to the creation of a new save file, but the game cannot resume from that save file, making it pretty useless as far as save files are concerned.

**Comment by Teeyenoh** [comment]
Good find! The game currently doesn't generate new save files (I wrote the one you're using by hand!) so I'll work on that now :-)

**Comment by Teeyenoh** [comment]
Fixed in commit f7d387e8
