### ISSUE TITLE
[v0.5.3.1-alpha] Character creation - backspace

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#39]
When backspacing on the name section in the character creation where there is no letter (backspacing further than the text within the box goes), the game crashes with a StringIndexOutOfBounds Exception error.

**Comment by JuiceWarrior** [comment]
There is also no cursor mark when typing a name, making it needlessly difficult to navigate the menu.

**Comment by Teeyenoh** [comment]
Hmm I'll look at the backspace thing first but the cursor is not totally important right now, I'll still look at it though

**Comment by Teeyenoh** [comment]
Fixed in commit 7a60103
