### ISSUE TITLE
[v0.1.7-alpha] Fireballs Don't Damage Caster

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#4]
I CAN WALK INTO MY OWN FIREBALLS!

**Comment by Teeyenoh** [comment]
Just as you would be able to if it were real :-) I'll check it out, in theory they should damage you :-P

**Comment by JuiceWarrior** [comment]
Freaking Dylan doesn't even know how to write titles!

**Comment by Teeyenoh** [comment]
This seems to be worse now, they don't even say "miss" anymore :-P
