### ISSUE TITLE
[v0.1.3-alpha] Dylan reversed the controls AGAIN!

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/Zephis#4]
Dylan you absolute fool!

Controls are reversed horizontally!

Why are you so bad at this?

**Comment by Teeyenoh** [comment]
I've changed nothing since yesterday!!

**Comment by JuiceWarrior** [comment]
The worst part is obviously that they only reverse sometimes!

**Comment by JuiceWarrior** [comment]
I think it's because of the tower!

**Comment by Teeyenoh** [comment]
Is the tower still falling and bouncing correctly?

**Comment by JuiceWarrior** [comment]
THAT HAS NOTHING TO DO WITH THIS ISSUE!

**Comment by Teeyenoh** [comment]
Damnit you're right

**Comment by Teeyenoh** [comment]
I'll try clamping the camera tonight, see if that fixes it

**Comment by JuiceWarrior** [comment]
Gooooooooood

**Comment by Teeyenoh** [comment]
Clamped the camera, should be fixed
