### ISSUE TITLE
[v0.5.3.1-alpha] Character creation - stats screen

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#40]
The numbers to the right of the stats screen (ranging from -1 to +2) do not seem to correspond with changing the actual stats. They seem to increase at a rate of +1 every 2 points invested into a stat.

There does not seem to be any reason for this difference.

**Comment by Teeyenoh** [comment]
That's the stat's modifier, added to rolls in that stat. It is found by taking 10 from the stat, halving, rounding down, then adding half the level (rounded down). This is the standard D&D method of stats.
