### ISSUE TITLE
[v0.5.3.1-alpha] Saving inside walls

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#43]
I can confirm that saving inside of a wall will keep you inside the wall upon reloading. The program should remove people from objects that occupy the same tile as them in case someone becomes stuck on something in the final game.

**Comment by Teeyenoh** [comment]
There is no "wall object" so this isn't relevant.

**Comment by JuiceWarrior** [comment]
Let me reword this then, if a character is on something that has a hitbox, they should be removed from that object upon reloading, rather than remaining there. I think walls should have hitboxes :P
