### ISSUE TITLE
[v0.5.3.1-alpha] Saving mid-motion

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#44]
When saving at the start of an animation, the entire animation will resume upon reloading the game. When moving between tiles, the game should ideally skip the animation upon reloading and should place the character model on the tile they were travelling towards; assuming they could travel towards it in the first place.

**Comment by Teeyenoh** [comment]
I've designed it this way because not all moving animations will be as quick as the players, and save-loading could be used to alter movement etc.
