### ISSUE TITLE
Note to Dylan

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#5]
Yeah, I don't think having enemies on the overworld like this is particularly good, I can see this getting very annoying later on...

**Comment by Teeyenoh** [comment]
There is no overworld / combat dichotomy, this is how combat will function :-)

**Comment by JuiceWarrior** [comment]
BUT THAT WON'T WORK!

**Comment by JuiceWarrior** [comment]
Purely basing this off how enemies currently move, it's going to be so frustrating just getting around if this is how combat is going to work!

**Comment by Teeyenoh** [comment]
'twill!

**Comment by Teeyenoh** [comment]
It will be slightly different, this is just a demo :-)

**Comment by JuiceWarrior** [comment]
Could I enquire exactly how you plan to fix this? It's already very annoying, too annoying to be even close to enjoyable

**Comment by Teeyenoh** [comment]
What exactly is the issue?

**Comment by JuiceWarrior** [comment]
Pretty much this entire system. In this case, the enemy is almost impossible to avoid, attacks too often, follows you around like a nuisance, them being immovable makes simple navigation a pain, not to mention it's going to get even worse once follower allies have been implemented, making them even more annoying and even harder to avoid.

**Comment by Teeyenoh** [comment]
The enemy can't be avoided because he's relentlessly aggressive with nothing in place to "lower" his intelligence. The attack speed is currently arbitrary and will likely function differently quite soon. You're not meant to move through him, you're meant to fight him or run away :-P

**Comment by JuiceWarrior** [comment]
But with more allies, fighting or running away no longer becomes a viable strategy, you would almost always HAVE to be engaged by the enemy because you have a larger presence and larger hitbox, making combat almost unavoidable should you happen to run into an enemy.
