### ISSUE TITLE
[v0.1.8-alpha] GUI feedback

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#6]
Slightly strange, but the health bar is longer than the mana bar, even though you have less health than mana :P

**Comment by JuiceWarrior** [comment]
Also, you can have negative mana, it seems

**Comment by JuiceWarrior** [comment]
Numbers on the GUI seem slightly cramped and the width of the numbers changes often making it harder to read at larger values (>1000)

**Comment by Teeyenoh** [comment]
For future reference, please could you drop separate bugs into different issues so they're easier to track? Thanks :-)

I was planning on having the player's bars the same length, but I'm open to change! Although we'd best discuss it again after I've added in the stamina bar :-P

Yes, you can! Definitely drop this in a separate issue for me, as this needs addressing quickly :-(

I'll take a look at this, but fixing it might take a large rewrite of the text drawing engine which I am loathe to do right now :-( stick it in a separate issue and I'll change it at some point!

**Comment by JuiceWarrior** [comment]
Ugh, fine. Hold on
