### ISSUE TITLE
[v0.1.0-alpha] Character mobility needs to be seriously improved

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#6]
Character movement is simply too stiff to be enjoyable, the model takes too long to register minute changes in direction and sometimes does not register those changes at all unless they are input at the moment the model stops moving, any sooner and it will not register.

**Comment by JuiceWarrior** [comment]
The only exception occurs when you hold the button down to continue moving, however, considering the world layout, this is not possible for multi-directional movement

**Comment by Teeyenoh** [comment]
I've increased the grid size by a factor of two, this should reduce the issue
