### ISSUE TITLE
[v0.1.8-alpha] No Enemy Health Bars

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#7]
Enemies seem to have lost their title and health bars. I don't understand why you changed this.

**Comment by JuiceWarrior** [comment]
There's another problem with the enemies, but due to lack of ability to properly test these things, I've put it into a separate issue

**Comment by Teeyenoh** [comment]
Ah yes they have! I didn't even notice this :-P I'd imagine they're actually behind the panel as I was having layering issues with the other one too :-) I'll postpone this slightly until the GUI is more softcoded however :-)
