### ISSUE TITLE
Report 1: Map menu [v0.1.2-alpha]

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#7]
There is a visible grid across the grassy tiles, it's very distracting and strange. These need to be removed ASAP!

**Comment by Teeyenoh** [comment]
That's a side effect of the random textures, those "gridlike" grass tiles are actually the edges of cliffs :-)

**Comment by JuiceWarrior** [comment]
They're not on cliff edges though :P And if they are, then they sure don't seem like it
