### ISSUE TITLE
[v0.1.8-alpha] Enemies Can Pass Through Player

### ISSUE THREAD

**Issue by JuiceWarrior** [Teeyenoh/zephis#8]
So... I can't walk through enemies but enemies can walk through me...?

**Comment by Teeyenoh** [comment]
I can't replicate this! When do enemies walk through you?

**Comment by JuiceWarrior** [comment]
It seems to be random, it occurs when an enemy dies; sometimes they will walk onto your space and die, instead of dying on their own space.

So rude.

**Comment by Teeyenoh** [comment]
Hmm, I'll see if it pops up at any point!

**Comment by Teeyenoh** [comment]
I've just managed to replicate this! Do you find it happens when you cast fireballs right next to enemies?

**Comment by JuiceWarrior** [comment]
Nah, it mainly occurs whenever I kill an enemy with melee attacks.

**Comment by Teeyenoh** [comment]
Hmm, well without a solid way to replicate it it'll be hard to fix :-(
